import type { BiolinkProfile } from "./biolink-store"

export interface Template {
  id: string
  name: string
  description: string
  category: string
  thumbnail: string
  isPro?: boolean
  profile: Omit<BiolinkProfile, "id" | "username" | "createdAt" | "updatedAt">
}

export interface PredefinedBackground {
  id: string
  name: string
  backgroundColor?: string
  backgroundImageUrl?: string
}

export const PREDEFINED_BACKGROUNDS: PredefinedBackground[] = [
  {
    id: "abstract-local-1",
    name: "Abstracto Local 1",
    backgroundImageUrl: "/backgrounds/abstract1.svg",
  },
  {
    id: "geometric-local-2",
    name: "Geométrico Local 2",
    backgroundImageUrl: "/backgrounds/geometric2.svg",
  },
  {
    id: "nature-local-3",
    name: "Naturaleza Local 3",
    backgroundImageUrl: "/backgrounds/nature3.svg",
  },
  {
    id: "city-local-4",
    name: "Ciudad Local 4",
    backgroundImageUrl: "/backgrounds/city4.svg",
  },
  {
    id: "pattern-local-5",
    name: "Patrón Local 5",
    backgroundImageUrl: "/backgrounds/pattern5.svg",
  },
  {
    id: "default-light",
    name: "Claro Predeterminado",
    backgroundColor: "#ffffff",
  },
  {
    id: "default-dark",
    name: "Oscuro Predeterminado",
    backgroundColor: "#1a1a1a",
  },
  {
    id: "gradient-blue",
    name: "Gradiente Azul",
    backgroundImageUrl: "linear-gradient(to right, #4facfe 0%, #00f2fe 100%)",
  },
  {
    id: "gradient-purple",
    name: "Gradiente Púrpura",
    backgroundImageUrl: "linear-gradient(to right, #fbc2eb 0%, #a6c1ee 100%)",
  },
  {
    id: "nature-forest",
    name: "Bosque Natural",
    backgroundImageUrl: "https://picsum.photos/seed/nature/1920/1080",
  },
  {
    id: "city-night",
    name: "Ciudad Nocturna",
    backgroundImageUrl: "https://picsum.photos/seed/city/1920/1080",
  },
  {
    id: "abstract-geometric",
    name: "Geométrico Abstracto",
    backgroundImageUrl: "https://picsum.photos/seed/abstract/1920/1080",
  },
]

export const TEMPLATE_CATEGORIES = [
  { id: "all", name: "Todas" },
  { id: "creators", name: "Creadores" },
  { id: "business", name: "Negocios" },
  { id: "artists", name: "Artistas" },
  { id: "professionals", name: "Profesionales" },
  { id: "ecommerce", name: "E-commerce" },
  { id: "events", name: "Eventos" },
  { id: "health", name: "Salud" },
  { id: "education", name: "Educación" },
]

export const TEMPLATES: Template[] = [
  // =====================
  // CREATORS (8 templates)
  // =====================
  {
    id: "influencer",
    name: "Influencer",
    description: "Perfecto para creadores de contenido en redes sociales",
    category: "creators",
    thumbnail: "influencer social media creator colorful fashion",
    profile: {
      displayName: "Sofia Martinez",
      bio: "Content Creator | Lifestyle & Travel | 500K+ seguidores",
      avatar: "",
      theme: "influencer",
      backgroundColor: "#fce4ec",
      buttonStyle: "pill",
      buttonColor: "#e91e63",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Mi nuevo video viral", url: "https://youtube.com", enabled: true },
        { id: "2", title: "Colaboraciones", url: "https://example.com", enabled: true },
        { id: "3", title: "Mi tienda de merch", url: "https://example.com", enabled: true },
        { id: "4", title: "Podcast semanal", url: "https://spotify.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "youtube", url: "https://youtube.com", enabled: true },
        { platform: "tiktok", url: "https://tiktok.com", enabled: true },
      ],
    },
  },
  {
    id: "youtuber",
    name: "YouTuber Gaming",
    description: "Ideal para creadores de video y streamers",
    category: "creators",
    thumbnail: "gamer streamer neon gaming setup",
    profile: {
      displayName: "GamerPro",
      bio: "Gaming | Streams en vivo | Entretenimiento 24/7",
      avatar: "",
      theme: "youtuber",
      backgroundColor: "#0f0f1a",
      buttonStyle: "rounded",
      buttonColor: "#ff0000",
      textColor: "#ffffff",
      links: [
        { id: "1", title: "Canal de YouTube", url: "https://youtube.com", enabled: true },
        { id: "2", title: "Twitch Stream", url: "https://twitch.tv", enabled: true },
        { id: "3", title: "Discord Server", url: "https://discord.com", enabled: true },
        { id: "4", title: "Donaciones", url: "https://example.com", enabled: true },
        { id: "5", title: "Setup Gaming", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "youtube", url: "https://youtube.com", enabled: true },
        { platform: "twitter", url: "https://twitter.com", enabled: true },
        { platform: "tiktok", url: "https://tiktok.com", enabled: true },
      ],
    },
  },
  {
    id: "podcast",
    name: "Podcast",
    description: "Para podcasters y creadores de audio",
    category: "creators",
    thumbnail: "podcast microphone studio professional audio",
    profile: {
      displayName: "El Podcast Show",
      bio: "Conversaciones que inspiran | Nuevos episodios cada martes",
      avatar: "",
      theme: "podcast",
      backgroundColor: "#1a1a2e",
      buttonStyle: "rounded",
      buttonColor: "#9c27b0",
      textColor: "#ffffff",
      links: [
        { id: "1", title: "Escuchar en Spotify", url: "https://spotify.com", enabled: true },
        { id: "2", title: "Apple Podcasts", url: "https://apple.com", enabled: true },
        { id: "3", title: "YouTube Podcast", url: "https://youtube.com", enabled: true },
        { id: "4", title: "Episodio más reciente", url: "https://example.com", enabled: true },
        { id: "5", title: "Ser patrocinador", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "twitter", url: "https://twitter.com", enabled: true },
      ],
    },
  },
  {
    id: "tiktoker",
    name: "TikToker",
    description: "Para creadores de contenido corto y viral",
    category: "creators",
    thumbnail: "tiktoker young creator dancing trendy",
    profile: {
      displayName: "ValeTrends",
      bio: "Trends | Comedy | Dance | 1M TikTok",
      avatar: "",
      theme: "tiktoker",
      backgroundColor: "#000000",
      buttonStyle: "pill",
      buttonColor: "#fe2c55",
      textColor: "#ffffff",
      links: [
        { id: "1", title: "TikTok", url: "https://tiktok.com", enabled: true },
        { id: "2", title: "Instagram Reels", url: "https://instagram.com", enabled: true },
        { id: "3", title: "YouTube Shorts", url: "https://youtube.com", enabled: true },
        { id: "4", title: "Brand Collabs", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "tiktok", url: "https://tiktok.com", enabled: true },
        { platform: "instagram", url: "https://instagram.com", enabled: true },
      ],
    },
  },
  {
    id: "blogger",
    name: "Blogger",
    description: "Para escritores y creadores de contenido escrito",
    category: "creators",
    thumbnail: "blogger writer laptop coffee minimal",
    profile: {
      displayName: "Ana Escribe",
      bio: "Escritora | Blog de lifestyle | Newsletter semanal",
      avatar: "",
      theme: "blogger",
      backgroundColor: "#faf5f0",
      buttonStyle: "rounded",
      buttonColor: "#8b7355",
      textColor: "#3d3d3d",
      links: [
        { id: "1", title: "Leer mi blog", url: "https://example.com", enabled: true },
        { id: "2", title: "Newsletter gratuita", url: "https://example.com", enabled: true },
        { id: "3", title: "Mi libro nuevo", url: "https://amazon.com", enabled: true },
        { id: "4", title: "Colaboraciones", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "twitter", url: "https://twitter.com", enabled: true },
        { platform: "instagram", url: "https://instagram.com", enabled: true },
      ],
    },
  },
  {
    id: "vlogger-travel",
    name: "Travel Vlogger",
    description: "Para viajeros y creadores de contenido de viajes",
    category: "creators",
    thumbnail: "travel vlogger adventure mountains landscape",
    profile: {
      displayName: "Mundo Viajero",
      bio: "Explorando el mundo | 50+ países | Tips de viaje",
      avatar: "",
      theme: "travel",
      backgroundColor: "#e8f4f8",
      buttonStyle: "pill",
      buttonColor: "#0891b2",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Último video de viaje", url: "https://youtube.com", enabled: true },
        { id: "2", title: "Guías de viaje gratis", url: "https://example.com", enabled: true },
        { id: "3", title: "Mis presets de fotos", url: "https://example.com", enabled: true },
        { id: "4", title: "Equipo de viaje", url: "https://amazon.com", enabled: true },
      ],
      socialLinks: [
        { platform: "youtube", url: "https://youtube.com", enabled: true },
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "tiktok", url: "https://tiktok.com", enabled: true },
      ],
    },
  },
  {
    id: "beauty-creator",
    name: "Beauty Creator",
    description: "Para creadores de contenido de belleza y maquillaje",
    category: "creators",
    thumbnail: "beauty makeup artist glamorous pink",
    profile: {
      displayName: "Glam by Lucia",
      bio: "Makeup Artist | Beauty Tips | Tutoriales",
      avatar: "",
      theme: "beauty",
      backgroundColor: "#fff0f5",
      buttonStyle: "pill",
      buttonColor: "#db2777",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Tutorial de maquillaje", url: "https://youtube.com", enabled: true },
        { id: "2", title: "Mis productos favoritos", url: "https://example.com", enabled: true },
        { id: "3", title: "Cursos de maquillaje", url: "https://example.com", enabled: true },
        { id: "4", title: "Agenda tu cita", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "youtube", url: "https://youtube.com", enabled: true },
        { platform: "tiktok", url: "https://tiktok.com", enabled: true },
      ],
    },
  },
  {
    id: "fitness-creator",
    name: "Fitness Creator",
    description: "Para entrenadores y creadores de contenido fitness",
    category: "creators",
    thumbnail: "fitness trainer gym workout strong",
    profile: {
      displayName: "Fit con Carlos",
      bio: "Personal Trainer | Transformación física | Motivación",
      avatar: "",
      theme: "fitness",
      backgroundColor: "#1a1a1a",
      buttonStyle: "square",
      buttonColor: "#22c55e",
      textColor: "#ffffff",
      links: [
        { id: "1", title: "Rutina gratis de 30 días", url: "https://example.com", enabled: true },
        { id: "2", title: "Plan de nutrición", url: "https://example.com", enabled: true },
        { id: "3", title: "Coaching 1:1", url: "https://example.com", enabled: true },
        { id: "4", title: "Suplementos recomendados", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "youtube", url: "https://youtube.com", enabled: true },
      ],
    },
  },

  // =====================
  // BUSINESS (8 templates)
  // =====================
  {
    id: "restaurant",
    name: "Restaurante",
    description: "Menú digital, reservas y ubicación para tu restaurante",
    category: "business",
    thumbnail: "restaurant fine dining gourmet food elegant",
    profile: {
      displayName: "La Trattoria Italiana",
      bio: "Cocina italiana auténtica desde 1985 | Reservas disponibles",
      avatar: "",
      theme: "restaurant",
      backgroundColor: "#fef3c7",
      buttonStyle: "rounded",
      buttonColor: "#b45309",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Ver Menú Completo", url: "https://example.com/menu", enabled: true },
        { id: "2", title: "Hacer Reservación", url: "https://example.com", enabled: true },
        { id: "3", title: "Pedir a Domicilio", url: "https://example.com", enabled: true },
        { id: "4", title: "Menú de Vinos", url: "https://example.com", enabled: true },
        { id: "5", title: "Cómo Llegar", url: "https://maps.google.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "facebook", url: "https://facebook.com", enabled: true },
        { platform: "whatsapp", url: "https://wa.me", enabled: true },
      ],
    },
  },
  {
    id: "cafe",
    name: "Cafetería",
    description: "Para cafeterías y panaderías artesanales",
    category: "business",
    thumbnail: "coffee shop cafe cozy aesthetic latte art",
    profile: {
      displayName: "Coffee & Dreams",
      bio: "Café de especialidad | Repostería artesanal | WiFi gratis",
      avatar: "",
      theme: "cafe",
      backgroundColor: "#f5f0eb",
      buttonStyle: "pill",
      buttonColor: "#78350f",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Nuestro Menú", url: "https://example.com", enabled: true },
        { id: "2", title: "Pedir Online", url: "https://example.com", enabled: true },
        { id: "3", title: "Suscripción de café", url: "https://example.com", enabled: true },
        { id: "4", title: "Ubicación y horarios", url: "https://maps.google.com", enabled: true },
      ],
      socialLinks: [{ platform: "instagram", url: "https://instagram.com", enabled: true }],
    },
  },
  {
    id: "salon",
    name: "Salón de Belleza",
    description: "Ideal para estéticas, spas y salones",
    category: "business",
    thumbnail: "beauty salon spa elegant luxury treatment",
    profile: {
      displayName: "Glamour Studio",
      bio: "Tu belleza, nuestra pasión | Agenda tu cita online",
      avatar: "",
      theme: "salon",
      backgroundColor: "#fdf2f8",
      buttonStyle: "pill",
      buttonColor: "#be185d",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Agendar Cita", url: "https://example.com", enabled: true },
        { id: "2", title: "Nuestros Servicios", url: "https://example.com", enabled: true },
        { id: "3", title: "Galería de Trabajos", url: "https://example.com", enabled: true },
        { id: "4", title: "Promociones del Mes", url: "https://example.com", enabled: true },
        { id: "5", title: "Lista de Precios", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "facebook", url: "https://facebook.com", enabled: true },
        { platform: "whatsapp", url: "https://wa.me", enabled: true },
      ],
    },
  },
  {
    id: "barbershop",
    name: "Barbería",
    description: "Para barberías y peluquerías masculinas",
    category: "business",
    thumbnail: "barbershop vintage masculine grooming barber",
    profile: {
      displayName: "The Gentleman's Cut",
      bio: "Barbería tradicional | Cortes clásicos y modernos",
      avatar: "",
      theme: "barbershop",
      backgroundColor: "#1c1917",
      buttonStyle: "square",
      buttonColor: "#d97706",
      textColor: "#ffffff",
      links: [
        { id: "1", title: "Reservar Turno", url: "https://example.com", enabled: true },
        { id: "2", title: "Ver Servicios", url: "https://example.com", enabled: true },
        { id: "3", title: "Nuestros Barberos", url: "https://example.com", enabled: true },
        { id: "4", title: "Productos", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "whatsapp", url: "https://wa.me", enabled: true },
      ],
    },
  },
  {
    id: "gym",
    name: "Gimnasio",
    description: "Para gimnasios y centros fitness",
    category: "business",
    thumbnail: "gym fitness center modern equipment workout",
    profile: {
      displayName: "PowerFit Gym",
      bio: "Tu mejor versión empieza aquí | Abierto 24/7",
      avatar: "",
      theme: "gym",
      backgroundColor: "#0a0a0a",
      buttonStyle: "rounded",
      buttonColor: "#dc2626",
      textColor: "#ffffff",
      links: [
        { id: "1", title: "Membresías y Precios", url: "https://example.com", enabled: true },
        { id: "2", title: "Clase de prueba GRATIS", url: "https://example.com", enabled: true },
        { id: "3", title: "Horario de Clases", url: "https://example.com", enabled: true },
        { id: "4", title: "Nuestros Trainers", url: "https://example.com", enabled: true },
        { id: "5", title: "Ubicación", url: "https://maps.google.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "facebook", url: "https://facebook.com", enabled: true },
      ],
    },
  },
  {
    id: "hotel",
    name: "Hotel",
    description: "Para hoteles y hospedajes",
    category: "business",
    thumbnail: "hotel luxury resort pool tropical vacation",
    isPro: true,
    profile: {
      displayName: "Hotel Paradise",
      bio: "Tu escape perfecto | 5 estrellas | Frente al mar",
      avatar: "",
      theme: "hotel",
      backgroundColor: "#0c4a6e",
      buttonStyle: "pill",
      buttonColor: "#fbbf24",
      textColor: "#ffffff",
      links: [
        { id: "1", title: "Reservar Habitación", url: "https://example.com", enabled: true },
        { id: "2", title: "Ver Habitaciones", url: "https://example.com", enabled: true },
        { id: "3", title: "Restaurante y Spa", url: "https://example.com", enabled: true },
        { id: "4", title: "Ofertas Especiales", url: "https://example.com", enabled: true },
        { id: "5", title: "Contacto", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "facebook", url: "https://facebook.com", enabled: true },
      ],
    },
  },
  {
    id: "dental",
    name: "Clínica Dental",
    description: "Para dentistas y clínicas dentales",
    category: "business",
    thumbnail: "dental clinic modern clean professional dentist",
    profile: {
      displayName: "Sonrisas Dental",
      bio: "Tu sonrisa perfecta | Tecnología de vanguardia",
      avatar: "",
      theme: "dental",
      backgroundColor: "#ecfdf5",
      buttonStyle: "rounded",
      buttonColor: "#059669",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Agendar Cita", url: "https://example.com", enabled: true },
        { id: "2", title: "Nuestros Servicios", url: "https://example.com", enabled: true },
        { id: "3", title: "Conoce al equipo", url: "https://example.com", enabled: true },
        { id: "4", title: "Antes y Después", url: "https://example.com", enabled: true },
        { id: "5", title: "WhatsApp", url: "https://wa.me", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "facebook", url: "https://facebook.com", enabled: true },
      ],
    },
  },
  {
    id: "law-firm",
    name: "Despacho Legal",
    description: "Para abogados y despachos jurídicos",
    category: "business",
    thumbnail: "law firm professional office legal justice",
    isPro: true,
    profile: {
      displayName: "García & Asociados",
      bio: "Abogados | 20+ años de experiencia | Consulta gratuita",
      avatar: "",
      theme: "legal",
      backgroundColor: "#1e293b",
      buttonStyle: "square",
      buttonColor: "#94a3b8",
      textColor: "#ffffff",
      links: [
        { id: "1", title: "Consulta Gratuita", url: "https://example.com", enabled: true },
        { id: "2", title: "Áreas de Práctica", url: "https://example.com", enabled: true },
        { id: "3", title: "Nuestro Equipo", url: "https://example.com", enabled: true },
        { id: "4", title: "Casos de Éxito", url: "https://example.com", enabled: true },
        { id: "5", title: "Contactar", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "linkedin", url: "https://linkedin.com", enabled: true },
        { platform: "twitter", url: "https://twitter.com", enabled: true },
      ],
    },
  },

  // =====================
  // ARTISTS (6 templates)
  // =====================
  {
    id: "musician",
    name: "Músico/Banda",
    description: "Para artistas y bandas musicales",
    category: "artists",
    thumbnail: "musician rock band concert stage lights",
    profile: {
      displayName: "Luna Nova",
      bio: "Indie Rock | Nuevo álbum 'Eclipse' disponible",
      avatar: "",
      theme: "musician",
      backgroundColor: "#0f0f23",
      buttonStyle: "rounded",
      buttonColor: "#8b5cf6",
      textColor: "#ffffff",
      links: [
        { id: "1", title: "Escuchar en Spotify", url: "https://spotify.com", enabled: true },
        { id: "2", title: "Apple Music", url: "https://music.apple.com", enabled: true },
        { id: "3", title: "Nuevo Video Musical", url: "https://youtube.com", enabled: true },
        { id: "4", title: "Próximos Conciertos", url: "https://example.com", enabled: true },
        { id: "5", title: "Merch Oficial", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "youtube", url: "https://youtube.com", enabled: true },
        { platform: "tiktok", url: "https://tiktok.com", enabled: true },
      ],
    },
  },
  {
    id: "dj",
    name: "DJ / Productor",
    description: "Para DJs y productores musicales",
    category: "artists",
    thumbnail: "dj electronic music club neon lights party",
    profile: {
      displayName: "DJ Electra",
      bio: "Electronic Music Producer | Bookings Open Worldwide",
      avatar: "",
      theme: "dj",
      backgroundColor: "#0a0a0a",
      buttonStyle: "square",
      buttonColor: "#22d3ee",
      textColor: "#ffffff",
      links: [
        { id: "1", title: "SoundCloud", url: "https://soundcloud.com", enabled: true },
        { id: "2", title: "Beatport", url: "https://beatport.com", enabled: true },
        { id: "3", title: "Latest Mix", url: "https://example.com", enabled: true },
        { id: "4", title: "Booking & Events", url: "https://example.com", enabled: true },
        { id: "5", title: "Press Kit", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "twitter", url: "https://twitter.com", enabled: true },
      ],
    },
  },
  {
    id: "photographer",
    name: "Fotógrafo",
    description: "Portfolio para fotógrafos profesionales",
    category: "artists",
    thumbnail: "photographer professional camera studio artistic",
    profile: {
      displayName: "Marco Lens Studio",
      bio: "Fotografía de bodas, retratos y eventos | CDMX",
      avatar: "",
      theme: "photographer",
      backgroundColor: "#fafafa",
      buttonStyle: "square",
      buttonColor: "#171717",
      textColor: "#171717",
      links: [
        { id: "1", title: "Ver Portfolio", url: "https://example.com", enabled: true },
        { id: "2", title: "Paquetes y Precios", url: "https://example.com", enabled: true },
        { id: "3", title: "Agendar Sesión", url: "https://example.com", enabled: true },
        { id: "4", title: "Galería de Bodas", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "website", url: "https://example.com", enabled: true },
      ],
    },
  },
  {
    id: "visual-artist",
    name: "Artista Visual",
    description: "Para pintores, ilustradores y artistas visuales",
    category: "artists",
    thumbnail: "artist painter colorful abstract gallery studio",
    profile: {
      displayName: "Arte de Carmen",
      bio: "Artista Visual | Pinturas y murales | Comisiones abiertas",
      avatar: "",
      theme: "artist",
      backgroundColor: "#fef9c3",
      buttonStyle: "pill",
      buttonColor: "#ea580c",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Ver Galería", url: "https://example.com", enabled: true },
        { id: "2", title: "Tienda de Arte", url: "https://example.com", enabled: true },
        { id: "3", title: "Solicitar Comisión", url: "https://example.com", enabled: true },
        { id: "4", title: "Próximas Exposiciones", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "twitter", url: "https://twitter.com", enabled: true },
      ],
    },
  },
  {
    id: "actor",
    name: "Actor/Modelo",
    description: "Para actores, modelos y artistas escénicos",
    category: "artists",
    thumbnail: "actor model professional headshot theatrical",
    isPro: true,
    profile: {
      displayName: "Andrea Vega",
      bio: "Actriz | Modelo | Representada por CAA Agency",
      avatar: "",
      theme: "actor",
      backgroundColor: "#1a1a1a",
      buttonStyle: "rounded",
      buttonColor: "#f5f5f5",
      textColor: "#ffffff",
      links: [
        { id: "1", title: "Reel de Actuación", url: "https://vimeo.com", enabled: true },
        { id: "2", title: "Portfolio de Modelaje", url: "https://example.com", enabled: true },
        { id: "3", title: "IMDb", url: "https://imdb.com", enabled: true },
        { id: "4", title: "Contactar Agente", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "twitter", url: "https://twitter.com", enabled: true },
      ],
    },
  },
  {
    id: "tattoo-artist",
    name: "Tatuador",
    description: "Para tatuadores y estudios de tatuaje",
    category: "artists",
    thumbnail: "tattoo artist studio ink creative artistic",
    profile: {
      displayName: "Ink Master Alex",
      bio: "Tattoo Artist | Realismo & Neotradicional | CDMX",
      avatar: "",
      theme: "tattoo",
      backgroundColor: "#0c0c0c",
      buttonStyle: "square",
      buttonColor: "#dc2626",
      textColor: "#ffffff",
      links: [
        { id: "1", title: "Ver Portfolio", url: "https://example.com", enabled: true },
        { id: "2", title: "Agendar Cita", url: "https://example.com", enabled: true },
        { id: "3", title: "Diseños Disponibles", url: "https://example.com", enabled: true },
        { id: "4", title: "Cuidados del Tatuaje", url: "https://example.com", enabled: true },
        { id: "5", title: "WhatsApp", url: "https://wa.me", enabled: true },
      ],
      socialLinks: [{ platform: "instagram", url: "https://instagram.com", enabled: true }],
    },
  },

  // =====================
  // PROFESSIONALS (6 templates)
  // =====================
  {
    id: "freelancer",
    name: "Freelancer",
    description: "Para profesionales independientes y consultores",
    category: "professionals",
    thumbnail: "freelancer designer laptop modern workspace",
    profile: {
      displayName: "Ana Developer",
      bio: "Diseño Web & UX/UI | +5 años de experiencia | Disponible para proyectos",
      avatar: "",
      theme: "freelancer",
      backgroundColor: "#eff6ff",
      buttonStyle: "rounded",
      buttonColor: "#2563eb",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Ver Portfolio", url: "https://example.com", enabled: true },
        { id: "2", title: "Mis Servicios", url: "https://example.com", enabled: true },
        { id: "3", title: "Agendar Llamada", url: "https://calendly.com", enabled: true },
        { id: "4", title: "Descargar CV", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "linkedin", url: "https://linkedin.com", enabled: true },
        { platform: "twitter", url: "https://twitter.com", enabled: true },
        { platform: "website", url: "https://example.com", enabled: true },
      ],
    },
  },
  {
    id: "coach",
    name: "Coach/Mentor",
    description: "Para coaches, mentores y entrenadores",
    category: "professionals",
    thumbnail: "coach mentor business success professional",
    profile: {
      displayName: "Carlos Mindset Coach",
      bio: "Life & Business Coach | Transforma tu vida | +1000 clientes",
      avatar: "",
      theme: "coach",
      backgroundColor: "#f0fdf4",
      buttonStyle: "pill",
      buttonColor: "#15803d",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Agenda tu Sesión Gratis", url: "https://example.com", enabled: true },
        { id: "2", title: "Mis Programas", url: "https://example.com", enabled: true },
        { id: "3", title: "Testimonios", url: "https://example.com", enabled: true },
        { id: "4", title: "Curso Gratuito", url: "https://example.com", enabled: true },
        { id: "5", title: "Podcast", url: "https://spotify.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "youtube", url: "https://youtube.com", enabled: true },
        { platform: "linkedin", url: "https://linkedin.com", enabled: true },
      ],
    },
  },
  {
    id: "realtor",
    name: "Agente Inmobiliario",
    description: "Para agentes de bienes raíces",
    category: "professionals",
    thumbnail: "real estate agent professional luxury home",
    profile: {
      displayName: "María Realty",
      bio: "Tu hogar ideal te espera | 10+ años de experiencia | Top Agent 2024",
      avatar: "",
      theme: "realtor",
      backgroundColor: "#fff7ed",
      buttonStyle: "rounded",
      buttonColor: "#c2410c",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Propiedades Disponibles", url: "https://example.com", enabled: true },
        { id: "2", title: "Busco mi Casa Ideal", url: "https://example.com", enabled: true },
        { id: "3", title: "Quiero Vender mi Propiedad", url: "https://example.com", enabled: true },
        { id: "4", title: "Agendar Visita", url: "https://example.com", enabled: true },
        { id: "5", title: "WhatsApp Directo", url: "https://wa.me", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "facebook", url: "https://facebook.com", enabled: true },
        { platform: "linkedin", url: "https://linkedin.com", enabled: true },
      ],
    },
  },
  {
    id: "consultant",
    name: "Consultor",
    description: "Para consultores y asesores empresariales",
    category: "professionals",
    thumbnail: "consultant business professional corporate meeting",
    isPro: true,
    profile: {
      displayName: "Roberto Consulting",
      bio: "Consultor de Negocios | Estrategia & Growth | Ex-McKinsey",
      avatar: "",
      theme: "consultant",
      backgroundColor: "#f8fafc",
      buttonStyle: "square",
      buttonColor: "#0f172a",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Solicitar Consultoría", url: "https://example.com", enabled: true },
        { id: "2", title: "Servicios", url: "https://example.com", enabled: true },
        { id: "3", title: "Casos de Estudio", url: "https://example.com", enabled: true },
        { id: "4", title: "Mi Libro", url: "https://amazon.com", enabled: true },
        { id: "5", title: "LinkedIn", url: "https://linkedin.com", enabled: true },
      ],
      socialLinks: [
        { platform: "linkedin", url: "https://linkedin.com", enabled: true },
        { platform: "twitter", url: "https://twitter.com", enabled: true },
      ],
    },
  },
  {
    id: "therapist",
    name: "Terapeuta/Psicólogo",
    description: "Para terapeutas y profesionales de salud mental",
    category: "professionals",
    thumbnail: "therapist psychologist calm peaceful wellness",
    profile: {
      displayName: "Dra. Laura Paz",
      bio: "Psicóloga Clínica | Terapia online y presencial | Citas disponibles",
      avatar: "",
      theme: "therapist",
      backgroundColor: "#faf5ff",
      buttonStyle: "pill",
      buttonColor: "#7c3aed",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Agendar Cita", url: "https://example.com", enabled: true },
        { id: "2", title: "Servicios de Terapia", url: "https://example.com", enabled: true },
        { id: "3", title: "Sobre Mí", url: "https://example.com", enabled: true },
        { id: "4", title: "Blog de Bienestar", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "linkedin", url: "https://linkedin.com", enabled: true },
      ],
    },
  },
  {
    id: "accountant",
    name: "Contador",
    description: "Para contadores y asesores fiscales",
    category: "professionals",
    thumbnail: "accountant financial advisor office professional",
    profile: {
      displayName: "Contabilidad Pérez",
      bio: "Contador Público | Asesoría Fiscal | Declaraciones y más",
      avatar: "",
      theme: "accountant",
      backgroundColor: "#f0f9ff",
      buttonStyle: "rounded",
      buttonColor: "#0369a1",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Solicitar Cotización", url: "https://example.com", enabled: true },
        { id: "2", title: "Servicios Contables", url: "https://example.com", enabled: true },
        { id: "3", title: "Calculadora de Impuestos", url: "https://example.com", enabled: true },
        { id: "4", title: "Agendar Consulta", url: "https://calendly.com", enabled: true },
        { id: "5", title: "WhatsApp", url: "https://wa.me", enabled: true },
      ],
      socialLinks: [
        { platform: "linkedin", url: "https://linkedin.com", enabled: true },
        { platform: "facebook", url: "https://facebook.com", enabled: true },
      ],
    },
  },

  // =====================
  // E-COMMERCE (5 templates)
  // =====================
  {
    id: "fashion-shop",
    name: "Tienda de Moda",
    description: "Para tiendas de ropa y accesorios",
    category: "ecommerce",
    thumbnail: "fashion store clothing boutique stylish modern",
    profile: {
      displayName: "StyleBox Boutique",
      bio: "Moda urbana para todos | Envío gratis en compras +$999",
      avatar: "",
      theme: "fashion",
      backgroundColor: "#fafafa",
      buttonStyle: "square",
      buttonColor: "#171717",
      textColor: "#171717",
      links: [
        { id: "1", title: "Ir a la Tienda", url: "https://example.com", enabled: true },
        { id: "2", title: "Nueva Colección", url: "https://example.com", enabled: true },
        { id: "3", title: "Ofertas y Descuentos", url: "https://example.com", enabled: true },
        { id: "4", title: "Guía de Tallas", url: "https://example.com", enabled: true },
        { id: "5", title: "WhatsApp Ventas", url: "https://wa.me", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "tiktok", url: "https://tiktok.com", enabled: true },
      ],
    },
  },
  {
    id: "handmade",
    name: "Artesanías",
    description: "Para artesanos y productos hechos a mano",
    category: "ecommerce",
    thumbnail: "handmade crafts artisan jewelry creative",
    profile: {
      displayName: "Arte Manual",
      bio: "Joyería artesanal única | Cada pieza cuenta una historia",
      avatar: "",
      theme: "handmade",
      backgroundColor: "#fef2f2",
      buttonStyle: "pill",
      buttonColor: "#b91c1c",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Ver Catálogo", url: "https://example.com", enabled: true },
        { id: "2", title: "Pedidos Personalizados", url: "https://example.com", enabled: true },
        { id: "3", title: "Tienda Etsy", url: "https://etsy.com", enabled: true },
        { id: "4", title: "Proceso de Creación", url: "https://example.com", enabled: true },
      ],
      socialLinks: [{ platform: "instagram", url: "https://instagram.com", enabled: true }],
    },
  },
  {
    id: "food-delivery",
    name: "Comida & Delivery",
    description: "Para negocios de comida y delivery",
    category: "ecommerce",
    thumbnail: "food delivery restaurant delicious meal takeout",
    profile: {
      displayName: "Delicias Express",
      bio: "Comida casera a tu puerta | Pedidos por WhatsApp",
      avatar: "",
      theme: "food",
      backgroundColor: "#fef9c3",
      buttonStyle: "rounded",
      buttonColor: "#ca8a04",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Ver Menú del Día", url: "https://example.com", enabled: true },
        { id: "2", title: "Pedir por WhatsApp", url: "https://wa.me", enabled: true },
        { id: "3", title: "Uber Eats", url: "https://ubereats.com", enabled: true },
        { id: "4", title: "Rappi", url: "https://rappi.com", enabled: true },
        { id: "5", title: "Didi Food", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "facebook", url: "https://facebook.com", enabled: true },
      ],
    },
  },
  {
    id: "digital-products",
    name: "Productos Digitales",
    description: "Para vender cursos, ebooks y productos digitales",
    category: "ecommerce",
    thumbnail: "digital products courses online education ebook",
    isPro: true,
    profile: {
      displayName: "Digital Academy",
      bio: "Cursos online | E-books | Recursos digitales premium",
      avatar: "",
      theme: "digital",
      backgroundColor: "#eef2ff",
      buttonStyle: "rounded",
      buttonColor: "#4f46e5",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Ver Todos los Cursos", url: "https://example.com", enabled: true },
        { id: "2", title: "E-book Gratis", url: "https://example.com", enabled: true },
        { id: "3", title: "Membresía Premium", url: "https://example.com", enabled: true },
        { id: "4", title: "Recursos Gratuitos", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "youtube", url: "https://youtube.com", enabled: true },
      ],
    },
  },
  {
    id: "cosmetics",
    name: "Cosméticos",
    description: "Para tiendas de cosméticos y skincare",
    category: "ecommerce",
    thumbnail: "cosmetics beauty skincare products elegant luxury",
    profile: {
      displayName: "Glow Beauty Shop",
      bio: "Skincare & Makeup | Productos premium | Envío nacional",
      avatar: "",
      theme: "cosmetics",
      backgroundColor: "#fdf4ff",
      buttonStyle: "pill",
      buttonColor: "#a21caf",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Ir a la Tienda", url: "https://example.com", enabled: true },
        { id: "2", title: "Bestsellers", url: "https://example.com", enabled: true },
        { id: "3", title: "Rutina de Skincare", url: "https://example.com", enabled: true },
        { id: "4", title: "Ofertas", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "tiktok", url: "https://tiktok.com", enabled: true },
      ],
    },
  },

  // =====================
  // EVENTS (4 templates)
  // =====================
  {
    id: "wedding",
    name: "Boda",
    description: "Para invitaciones de boda digitales",
    category: "events",
    thumbnail: "wedding elegant romantic flowers couple celebration",
    isPro: true,
    profile: {
      displayName: "Ana & Carlos",
      bio: "¡Nos casamos! | 15 de Marzo 2025 | CDMX",
      avatar: "",
      theme: "wedding",
      backgroundColor: "#fdf2f8",
      buttonStyle: "pill",
      buttonColor: "#be185d",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Confirmar Asistencia", url: "https://example.com", enabled: true },
        { id: "2", title: "Nuestra Historia", url: "https://example.com", enabled: true },
        { id: "3", title: "Mesa de Regalos", url: "https://example.com", enabled: true },
        { id: "4", title: "Ubicación del Evento", url: "https://maps.google.com", enabled: true },
        { id: "5", title: "Dress Code", url: "https://example.com", enabled: true },
      ],
      socialLinks: [],
    },
  },
  {
    id: "event-organizer",
    name: "Organizador de Eventos",
    description: "Para organizadores y productores de eventos",
    category: "events",
    thumbnail: "event party celebration concert festival lights",
    profile: {
      displayName: "Epic Events MX",
      bio: "Productora de eventos | Conciertos | Festivales | Fiestas",
      avatar: "",
      theme: "events",
      backgroundColor: "#0f0f0f",
      buttonStyle: "rounded",
      buttonColor: "#f97316",
      textColor: "#ffffff",
      links: [
        { id: "1", title: "Próximos Eventos", url: "https://example.com", enabled: true },
        { id: "2", title: "Comprar Boletos", url: "https://example.com", enabled: true },
        { id: "3", title: "Galería de Eventos", url: "https://example.com", enabled: true },
        { id: "4", title: "Cotizar tu Evento", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "facebook", url: "https://facebook.com", enabled: true },
        { platform: "tiktok", url: "https://tiktok.com", enabled: true },
      ],
    },
  },
  {
    id: "birthday",
    name: "Cumpleaños",
    description: "Para invitaciones de cumpleaños",
    category: "events",
    thumbnail: "birthday party celebration balloons confetti cake",
    profile: {
      displayName: "¡Fiesta de Emma!",
      bio: "Celebramos mis 30 | Sábado 20 de Abril | ¡Te esperamos!",
      avatar: "",
      theme: "birthday",
      backgroundColor: "#fef3c7",
      buttonStyle: "pill",
      buttonColor: "#d97706",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Confirmar Asistencia", url: "https://example.com", enabled: true },
        { id: "2", title: "Ubicación de la Fiesta", url: "https://maps.google.com", enabled: true },
        { id: "3", title: "Lista de Deseos", url: "https://example.com", enabled: true },
        { id: "4", title: "Fotos de la Fiesta", url: "https://example.com", enabled: true },
      ],
      socialLinks: [],
    },
  },
  {
    id: "conference",
    name: "Conferencia",
    description: "Para conferencias y eventos corporativos",
    category: "events",
    thumbnail: "conference business corporate seminar professional",
    isPro: true,
    profile: {
      displayName: "Tech Summit 2025",
      bio: "El evento tech más grande de LATAM | 15-17 Mayo | CDMX",
      avatar: "",
      theme: "conference",
      backgroundColor: "#1e1b4b",
      buttonStyle: "square",
      buttonColor: "#6366f1",
      textColor: "#ffffff",
      links: [
        { id: "1", title: "Comprar Entradas", url: "https://example.com", enabled: true },
        { id: "2", title: "Agenda del Evento", url: "https://example.com", enabled: true },
        { id: "3", title: "Speakers", url: "https://example.com", enabled: true },
        { id: "4", title: "Patrocinadores", url: "https://example.com", enabled: true },
        { id: "5", title: "Ubicación", url: "https://maps.google.com", enabled: true },
      ],
      socialLinks: [
        { platform: "linkedin", url: "https://linkedin.com", enabled: true },
        { platform: "twitter", url: "https://twitter.com", enabled: true },
      ],
    },
  },

  // =====================
  // HEALTH (4 templates)
  // =====================
  {
    id: "doctor",
    name: "Médico",
    description: "Para médicos y especialistas de la salud",
    category: "health",
    thumbnail: "doctor medical professional healthcare clinic",
    profile: {
      displayName: "Dr. Roberto Salud",
      bio: "Médico General | Consulta presencial y online | 15+ años",
      avatar: "",
      theme: "doctor",
      backgroundColor: "#f0f9ff",
      buttonStyle: "rounded",
      buttonColor: "#0284c7",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Agendar Cita", url: "https://example.com", enabled: true },
        { id: "2", title: "Consulta Online", url: "https://example.com", enabled: true },
        { id: "3", title: "Especialidades", url: "https://example.com", enabled: true },
        { id: "4", title: "Ubicación del Consultorio", url: "https://maps.google.com", enabled: true },
        { id: "5", title: "WhatsApp", url: "https://wa.me", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "facebook", url: "https://facebook.com", enabled: true },
      ],
    },
  },
  {
    id: "nutritionist",
    name: "Nutriólogo",
    description: "Para nutriólogos y especialistas en alimentación",
    category: "health",
    thumbnail: "nutritionist healthy food diet wellness green",
    profile: {
      displayName: "Nutrición con Paula",
      bio: "Nutrióloga Certificada | Planes personalizados | Online",
      avatar: "",
      theme: "nutrition",
      backgroundColor: "#ecfdf5",
      buttonStyle: "pill",
      buttonColor: "#059669",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Agendar Consulta", url: "https://example.com", enabled: true },
        { id: "2", title: "Planes de Nutrición", url: "https://example.com", enabled: true },
        { id: "3", title: "Recetas Saludables", url: "https://example.com", enabled: true },
        { id: "4", title: "E-book Gratis", url: "https://example.com", enabled: true },
        { id: "5", title: "Testimonios", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "youtube", url: "https://youtube.com", enabled: true },
      ],
    },
  },
  {
    id: "yoga-studio",
    name: "Yoga & Wellness",
    description: "Para estudios de yoga y bienestar",
    category: "health",
    thumbnail: "yoga meditation wellness peaceful zen studio",
    profile: {
      displayName: "Zen Yoga Studio",
      bio: "Yoga | Meditación | Bienestar integral | Clases presenciales y online",
      avatar: "",
      theme: "yoga",
      backgroundColor: "#faf5ff",
      buttonStyle: "pill",
      buttonColor: "#9333ea",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Horario de Clases", url: "https://example.com", enabled: true },
        { id: "2", title: "Clase de Prueba Gratis", url: "https://example.com", enabled: true },
        { id: "3", title: "Membresías", url: "https://example.com", enabled: true },
        { id: "4", title: "Retiros de Yoga", url: "https://example.com", enabled: true },
        { id: "5", title: "Tienda Online", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "youtube", url: "https://youtube.com", enabled: true },
      ],
    },
  },
  {
    id: "veterinarian",
    name: "Veterinario",
    description: "Para veterinarios y clínicas de mascotas",
    category: "health",
    thumbnail: "veterinarian pet clinic dog cat animal care",
    profile: {
      displayName: "Clínica Veterinaria Happy Pets",
      bio: "Cuidamos a tu mejor amigo | Urgencias 24/7 | CDMX",
      avatar: "",
      theme: "vet",
      backgroundColor: "#f0fdf4",
      buttonStyle: "rounded",
      buttonColor: "#16a34a",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Agendar Cita", url: "https://example.com", enabled: true },
        { id: "2", title: "Servicios", url: "https://example.com", enabled: true },
        { id: "3", title: "Urgencias 24/7", url: "https://wa.me", enabled: true },
        { id: "4", title: "Tienda de Mascotas", url: "https://example.com", enabled: true },
        { id: "5", title: "Ubicación", url: "https://maps.google.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "facebook", url: "https://facebook.com", enabled: true },
      ],
    },
  },

  // =====================
  // EDUCATION (4 templates)
  // =====================
  {
    id: "teacher",
    name: "Profesor/Tutor",
    description: "Para profesores y tutores privados",
    category: "education",
    thumbnail: "teacher education classroom learning books",
    profile: {
      displayName: "Prof. Miguel Enseña",
      bio: "Matemáticas & Física | Clases particulares | Online y presencial",
      avatar: "",
      theme: "teacher",
      backgroundColor: "#fef3c7",
      buttonStyle: "rounded",
      buttonColor: "#b45309",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Agendar Clase", url: "https://example.com", enabled: true },
        { id: "2", title: "Materias que Imparto", url: "https://example.com", enabled: true },
        { id: "3", title: "Recursos Gratis", url: "https://example.com", enabled: true },
        { id: "4", title: "Testimonios de Alumnos", url: "https://example.com", enabled: true },
        { id: "5", title: "WhatsApp", url: "https://wa.me", enabled: true },
      ],
      socialLinks: [
        { platform: "youtube", url: "https://youtube.com", enabled: true },
        { platform: "instagram", url: "https://instagram.com", enabled: true },
      ],
    },
  },
  {
    id: "online-course",
    name: "Creador de Cursos",
    description: "Para creadores de cursos online",
    category: "education",
    thumbnail: "online course education learning laptop digital",
    isPro: true,
    profile: {
      displayName: "Academia Digital Pro",
      bio: "Aprende habilidades del futuro | +50 cursos | +10,000 estudiantes",
      avatar: "",
      theme: "academy",
      backgroundColor: "#1e1b4b",
      buttonStyle: "rounded",
      buttonColor: "#818cf8",
      textColor: "#ffffff",
      links: [
        { id: "1", title: "Ver Todos los Cursos", url: "https://example.com", enabled: true },
        { id: "2", title: "Curso Gratis de Prueba", url: "https://example.com", enabled: true },
        { id: "3", title: "Membresía Premium", url: "https://example.com", enabled: true },
        { id: "4", title: "Testimonios", url: "https://example.com", enabled: true },
        { id: "5", title: "Blog Educativo", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "youtube", url: "https://youtube.com", enabled: true },
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "linkedin", url: "https://linkedin.com", enabled: true },
      ],
    },
  },
  {
    id: "language-teacher",
    name: "Profesor de Idiomas",
    description: "Para profesores de idiomas",
    category: "education",
    thumbnail: "language teacher multilingual learning international",
    profile: {
      displayName: "English with Sarah",
      bio: "Profesora de Inglés Nativa | TOEFL | IELTS | Conversación",
      avatar: "",
      theme: "language",
      backgroundColor: "#eff6ff",
      buttonStyle: "pill",
      buttonColor: "#2563eb",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Clase de Prueba Gratis", url: "https://example.com", enabled: true },
        { id: "2", title: "Paquetes de Clases", url: "https://example.com", enabled: true },
        { id: "3", title: "Preparación TOEFL/IELTS", url: "https://example.com", enabled: true },
        { id: "4", title: "Recursos Gratuitos", url: "https://example.com", enabled: true },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "youtube", url: "https://youtube.com", enabled: true },
      ],
    },
  },
  {
    id: "music-teacher",
    name: "Profesor de Música",
    description: "Para profesores de música e instrumentos",
    category: "education",
    thumbnail: "music teacher piano guitar lessons instruments",
    profile: {
      displayName: "Clases de Guitarra con Juan",
      bio: "Aprende guitarra desde cero | Todos los niveles | Online",
      avatar: "",
      theme: "music-education",
      backgroundColor: "#fef2f2",
      buttonStyle: "rounded",
      buttonColor: "#dc2626",
      textColor: "#1a1a1a",
      links: [
        { id: "1", title: "Agendar Clase de Prueba", url: "https://example.com", enabled: true },
        { id: "2", title: "Paquetes de Clases", url: "https://example.com", enabled: true },
        { id: "3", title: "Tutoriales Gratis", url: "https://youtube.com", enabled: true },
        { id: "4", title: "Mi Canal de YouTube", url: "https://youtube.com", enabled: true },
      ],
      socialLinks: [
        { platform: "youtube", url: "https://youtube.com", enabled: true },
        { platform: "instagram", url: "https://instagram.com", enabled: true },
        { platform: "tiktok", url: "https://tiktok.com", enabled: true },
      ],
    },
  },
]

export function getTemplateById(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id)
}

export function getTemplatesByCategory(category: string): Template[] {
  if (category === "all") return TEMPLATES
  return TEMPLATES.filter((t) => t.category === category)
}
