/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "sffceokcuzdwtfhtkipi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmZmNlb2tjdXpkd3RmaHRraXBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNzE2ODgsImV4cCI6MjA3Nzk0NzY4OH0.ERDdva8m4eD3E35md-ke8nsgx2NdXj2lHW8GR7-0_KY"